import 'package:flutter_test/flutter_test.dart';
import 'package:seker_takip/core/constants.dart';

void main() {
  group('Bildirim payload sabitleri', () {
    test('tokluk payload tanımlı', () {
      expect(kPayloadToklukReminder, 'PAYLOAD_TOKLUK_REMINDER');
    });

    test('açlık payload tanımlı', () {
      expect(kPayloadAclikReminder, 'PAYLOAD_ACLIK_REMINDER');
    });

    test('bildirim ID tekil', () {
      expect(kNotifToklukId, isNot(equals(kNotifAclikId)));
    });
  });

  group('PDF branding sabitleri', () {
    test('header org tanımlı', () {
      expect(Tr.pdfHeaderOrg, 'Rootcastle Medical Systems');
    });

    test('footer gen tanımlı', () {
      expect(Tr.pdfFooterGen, 'Generated by Rootcastle AI');
    });
  });

  group('TTS sabitleri', () {
    test('sistem başlatıldı mesajı tanımlı', () {
      expect(Tr.sesSistemBaslatildi, isNotEmpty);
    });

    test('cihaz sessiz mesajı tanımlı', () {
      expect(Tr.sesCihazSessiz, isNotEmpty);
    });
  });

  group('Uygulama bilgileri', () {
    test('versiyon 1.1.0', () {
      expect(kAppVersion, '1.1.0');
    });

    test('geliştirici adı', () {
      expect(Tr.gelistiriciAdi, 'Batuhan Ayrıbaş');
    });
  });
}
